auth_key="ddodldl=$_"
api_password="Dec@17@20245"

AWS_ACCESS_KEY_ID=ZZZZZOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

GITHUB_TOKEN=ghp_example1234567890abcdefghijklm
